### ISSUE TITLE
Update dashboard icon

### ISSUE THREAD

**Issue by suhas2** [job-hax/frontend#46]
When in dashboard page show refresh icon:

![image](https://user-images.githubusercontent.com/8302550/55282696-cca84600-5306-11e9-888f-685a785f0766.png)

When not in dashboard page, show dashboard icon. Find an appropriate icon to use

**Comment by EgemenUslu** [comment]
@yinanq can you make a new icon for redirecting dashboard on header?

**Comment by yinanq** [comment]
“redirecting dashboard”? logo on header is the button to go to home page

**Comment by yinanq** [comment]
oh I see, a dashboard icon, I’ll make it by tomorrow

**Comment by EgemenUslu** [comment]
jobhax logo on header is redirecting to dashboard now, I dont remember well who but probably @suhas2 said that and I changed it from home to dashboard couple weeks ago. And the refresh icon is what we are asking to have a different image because it is redirecting to dashboard, not renewing the page. So when user in dashboard, this is fine but when in another page it shall be something related with dashboard. Or I can have this refresh png inside the dashboard body to sync&recall the backend and we can have one dashboard icon on header. What do you guys think?

**Comment by yinanq** [comment]
Actually I think that change was right. My original design of using logo to go to home page wasn’t good idea. Dashboard is the “home” for logged in user. I’ll make dashboard icon by tomorrow as quick solution for the refresh button, and then think if there’s a better structure for header, including your suggestion of moving refresh button out of it.

**Comment by EgemenUslu** [comment]
thank you
